pipeline {
    agent any
    stages {
        stage("Clean Up"){
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo"){
            steps {
                sh "git clone https://github.com/millenialprophet007/terraform.git"
            }
        }
        stage("Terraform Init"){
            steps {
                dir("terraform") {
                    sh "terraform init"
                }
            }
        }
        stage("Terraform Plan"){
            steps {
                dir("terraform") {
                    sh "terraform plan"
                }
            }
        }
        
        stage("Terraform Apply"){
            steps {
                dir("terraform") {
                    sh "terraform apply -auto-approve"
                }
            }
        }
    }
}
